### ISSUE TITLE
[FEATURE REQUEST]: new build system / packaging

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX-Desktop#555]
**Is your feature request related to a problem? Please describe.**

Switch to a new build system for faster build time / release

**Describe the solution you'd like**

- [x] use custom ports for our dependencies: https://github.com/KomodoPlatform/vcpkg-custom-ports
- [x] update to last [vcpkg](https://github.com/KomodoPlatform/vcpkg/commit/e9ff3cd5a04cd0e8122ff56e9873985ff71aa3ca) to enjoy overlay ports
- [x] use [unity build](https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html) for faster build with CMake (#549)
- [x] use [pch](https://cmake.org/cmake/help/git-stage/command/target_precompile_headers.html) for faster build with CMake (#549)
- [x] use shared library for shared deps between unit test and app for faster build (#549)
- [x] stop using windeployqt in ci script, it's done by CMake (#549)
- [x] Remove curl dependencies (#549)
- [x] Toolchain file is now included in the CMake cache (#549)
- [x] Set `CMAKE_CXX_COMPILER` by default to clang for windows/linux (#564)
- [ ] Use [vcpkg.json](https://vcpkg.readthedocs.io/en/latest/specifications/manifests/) instead of response file
- [x] Use `QT_INSTALL_CMAKE_PATH` from env in CMake cache to avoid usage with command line (#564)
- [x] Use make / ninja install instead of ci script for packaging on OSX
- [ ] Rename binaries correctly don't use double zip for artifacts cc @tonymorony 
- [x] Add appimage as extra artifacts for dev purpose #568 
- [x] Build a windows installer from CI 
- [ ] Sign the OSX bundle from the CI
- [x] Update the deps in the README.md to the new version
- [x] Update build instructions documentation once everything else is done
- [x] Add `vcpgk-custom-ports` as a submodule in the same directory as `vcpkg-repo` (and remove clone from CI)
- [x] Use reponse file in the ci script instead of manual installing package (#549)

**Describe alternatives you've considered**

- None

**Additional context**

- None

**Comment by tonymorony** [comment]
Implemented in 0.3.1
